# Generated by Django 5.2 on 2025-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
