# Generated by Django 5.0.7 on 2025-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_consultation_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_notes',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
