# Generated by Django 5.0.7 on 2025-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_appointment_consultation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_findings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
