# Generated by Django 5.0.7 on 2025-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
