# Generated by Django 5.0.7 on 2025-04-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.chatmessage'),
        ),
    ]
